---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kubeflow
  - network-policies.yaml

patches:
  - path: ./kserve-controller-manager-patch.yaml

configurations:
- params.yaml
