# Copyright 2026 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kserve
from kserve.models.v1beta1_kernel_cache_registry_config import V1beta1KernelCacheRegistryConfig  # noqa: E501
from kserve.rest import ApiException

class TestV1beta1KernelCacheRegistryConfig(unittest.TestCase):
    """V1beta1KernelCacheRegistryConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta1KernelCacheRegistryConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kserve.models.v1beta1_kernel_cache_registry_config.V1beta1KernelCacheRegistryConfig()  # noqa: E501
        if include_optional :
            return V1beta1KernelCacheRegistryConfig(
                auth = kserve.models.v1beta1_kernel_cache_registry_auth.V1beta1KernelCacheRegistryAuth(
                    pull_role_ref = kserve.models.v1beta1_kernel_cache_registry_role_ref.V1beta1KernelCacheRegistryRoleRef(
                        kind = 'ClusterRole',
                        name = 'registry-puller', ),
                    push_role_ref = kserve.models.v1beta1_kernel_cache_registry_role_ref.V1beta1KernelCacheRegistryRoleRef(
                        kind = 'ClusterRole',
                        name = 'registry-pusher', ),
                    token_ttl_seconds = 56,
                    type = '0', ), 
                ca_config_map_ref = kserve.models.v1beta1_kernel_cache_config_map_key_ref.V1beta1KernelCacheConfigMapKeyRef(
                    key = '0', 
                    name = '0', ), 
                endpoint = '0'
            )
        else :
            return V1beta1KernelCacheRegistryConfig(
        )

    def testV1beta1KernelCacheRegistryConfig(self):
        """Test V1beta1KernelCacheRegistryConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
