apiVersion: v1
kind: Service
metadata:
  name: kserve-webhook-server-service
  namespace: kserve
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: kserve-webhook-server-cert
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    control-plane: kserve-controller-manager
