---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../default
  - network-policies.yaml

patches:
  - path: kserve-controller-manager-patch.yaml

patchesStrategicMerge:
  - namespace-patch.yaml

configurations:
- params.yaml
