varReference:
  - path: spec/template/spec/containers/image
    kind: Deployment
    apiVersion: apps/v1
  - path: data
    kind: ConfigMap
    apiVersion: apps/v1
  - kind: CustomResourceDefinition
    path: spec/conversion/webhook/clientConfig/service/namespace
    apiVersion: apiextensions.k8s.io/v1    
