# Copyright 2026 The KServe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# coding: utf-8

"""
    KServe

    Python SDK for KServe  # noqa: E501

    The version of the OpenAPI document: v0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kserve.configuration import Configuration


class V1alpha1KernelCachePVCConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'access_modes': 'list[str]',
        'storage_class_name': 'str',
        'storage_size': 'ResourceQuantity',
        'volume_name': 'str'
    }

    attribute_map = {
        'access_modes': 'accessModes',
        'storage_class_name': 'storageClassName',
        'storage_size': 'storageSize',
        'volume_name': 'volumeName'
    }

    def __init__(self, access_modes=None, storage_class_name=None, storage_size=None, volume_name=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1KernelCachePVCConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._access_modes = None
        self._storage_class_name = None
        self._storage_size = None
        self._volume_name = None
        self.discriminator = None

        if access_modes is not None:
            self.access_modes = access_modes
        if storage_class_name is not None:
            self.storage_class_name = storage_class_name
        if storage_size is not None:
            self.storage_size = storage_size
        if volume_name is not None:
            self.volume_name = volume_name

    @property
    def access_modes(self):
        """Gets the access_modes of this V1alpha1KernelCachePVCConfig.  # noqa: E501

        AccessModes configures the PVC access modes.  # noqa: E501

        :return: The access_modes of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :rtype: list[str]
        """
        return self._access_modes

    @access_modes.setter
    def access_modes(self, access_modes):
        """Sets the access_modes of this V1alpha1KernelCachePVCConfig.

        AccessModes configures the PVC access modes.  # noqa: E501

        :param access_modes: The access_modes of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :type: list[str]
        """

        self._access_modes = access_modes

    @property
    def storage_class_name(self):
        """Gets the storage_class_name of this V1alpha1KernelCachePVCConfig.  # noqa: E501

        StorageClassName selects dynamic provisioning.  # noqa: E501

        :return: The storage_class_name of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :rtype: str
        """
        return self._storage_class_name

    @storage_class_name.setter
    def storage_class_name(self, storage_class_name):
        """Sets the storage_class_name of this V1alpha1KernelCachePVCConfig.

        StorageClassName selects dynamic provisioning.  # noqa: E501

        :param storage_class_name: The storage_class_name of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :type: str
        """

        self._storage_class_name = storage_class_name

    @property
    def storage_size(self):
        """Gets the storage_size of this V1alpha1KernelCachePVCConfig.  # noqa: E501


        :return: The storage_size of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :rtype: ResourceQuantity
        """
        return self._storage_size

    @storage_size.setter
    def storage_size(self, storage_size):
        """Sets the storage_size of this V1alpha1KernelCachePVCConfig.


        :param storage_size: The storage_size of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :type: ResourceQuantity
        """

        self._storage_size = storage_size

    @property
    def volume_name(self):
        """Gets the volume_name of this V1alpha1KernelCachePVCConfig.  # noqa: E501

        VolumeName binds to an existing PV.  # noqa: E501

        :return: The volume_name of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :rtype: str
        """
        return self._volume_name

    @volume_name.setter
    def volume_name(self, volume_name):
        """Sets the volume_name of this V1alpha1KernelCachePVCConfig.

        VolumeName binds to an existing PV.  # noqa: E501

        :param volume_name: The volume_name of this V1alpha1KernelCachePVCConfig.  # noqa: E501
        :type: str
        """

        self._volume_name = volume_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1KernelCachePVCConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1KernelCachePVCConfig):
            return True

        return self.to_dict() != other.to_dict()
